### ISSUE TITLE
Typo in README charts

### ISSUE THREAD

**Issue by belucid** [irresponsible/anarchy#2]
In the Actions section of the table, it should presumably say `PRINT "A==C"` rather than `PRINT "A==B"`.

**Comment by jjl** [comment]
Fixed now, sorry for the confusion and thanks for the bug report!

**Comment by belucid** [comment]
Cool. It's still wrong in the decision tree images. Looks like those are pulled from dtrules.com though. Maybe you can recreate them in Markdown though:

Conditions | 1 | 2 | 3 
-----------| --|---|--
A == 0 | Y | N |
B > 5 | | Y |
A == C | | | Y

**Comment by jjl** [comment]
Yes, sorry, I noticed this after my last commit. I've since updated the README with a note.

Markdown tables do seem like the way forward. I don't have time today for this, but I'd be happy to take a PR if you do :)

**Comment by belucid** [comment]
https://github.com/irresponsible/anarchy/pull/3
